server.port=8090
spring.application.name=clinic service

## PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/pearl_clinic_db
spring.datasource.username=moedaewi
spring.datasource.password=Loveumoemoe1399
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=vNx6LQ8QkD6r0Gm2sW3zTX7jvLWVv5P0lVbqvg4UGdM=
jwt.expiration=3600000

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/docs